FROM --platform=linux/amd64 node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./

ARG REACT_APP_ENV

RUN if [ "${REACT_APP_ENV}" = "development"]; \
        then npm install; \
        else npm install --only=production; \
        fi

COPY . .

ARG PORT

EXPOSE ${PORT}

CMD [ "npm", "run", "start" ]